import { describe, it, expect } from 'vitest';
// The committed fixture is a *synthetic* but byte-valid OLE2/CFB compound file
// in the pre-CS5 binary FLA layout (issue #8). It contains no Adobe content —
// it was generated by a minimal CFB writer and verified to round-trip through
// the `olefile` reference reader. It exercises BOTH stream paths: a small
// `Contents`/`Symbol 1` (mini-FAT) and a >4096-byte `Symbol 2` (regular FAT).
import binaryFlaUrl from './fixtures/binary-mx2004.fla?url';
import { isOLE2, OLE2File, OLE2_MAGIC } from '../ole2-reader';
import {
  extractBinaryFLAInfo,
  parseBinaryFLA,
} from '../binary-fla-parser';
import { FLAParser } from '../fla-parser';

async function loadFixtureBuffer(): Promise<ArrayBuffer> {
  const res = await fetch(binaryFlaUrl);
  return res.arrayBuffer();
}

async function loadFixtureBytes(): Promise<Uint8Array> {
  return new Uint8Array(await loadFixtureBuffer());
}

describe('isOLE2 magic detection', () => {
  it('detects the OLE2 compound-file signature', () => {
    expect(isOLE2(OLE2_MAGIC)).toBe(true);
    expect(isOLE2(new Uint8Array([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1, 0x00]))).toBe(true);
  });

  it('rejects a ZIP/XFL header ("PK") used by CS5+ FLAs', () => {
    // "PK\x03\x04" — the ZIP local-file-header signature.
    expect(isOLE2(new Uint8Array([0x50, 0x4b, 0x03, 0x04, 0x0a, 0x00]))).toBe(false);
  });

  it('rejects too-short input without throwing', () => {
    expect(isOLE2(new Uint8Array([0xd0, 0xcf]))).toBe(false);
    expect(isOLE2(new Uint8Array(0))).toBe(false);
  });
});

describe('OLE2File directory + stream reading', () => {
  it('lists the expected streams from a real-layout binary FLA', async () => {
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);
    const names = ole.listStreams().map((s) => s.name).sort();
    expect(names).toEqual(['Contents', 'Symbol 1', 'Symbol 2']);
    expect(ole.hasStream('Contents')).toBe(true);
    expect(ole.hasStream('DoesNotExist')).toBe(false);
  });

  it('reads a small (mini-FAT) stream and a large (FAT) stream correctly', async () => {
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);

    // Symbol 1 is below the 4096-byte mini-stream cutoff (mini-FAT path).
    const sym1 = ole.readStream('Symbol 1');
    expect(sym1.length).toBe(80);
    // MFC root header byte (0x01) followed by the FFFF new-class tag.
    expect(sym1[0]).toBe(0x01);
    expect(sym1[1]).toBe(0xff);
    expect(sym1[2]).toBe(0xff);

    // Symbol 2 is >4096 bytes (regular FAT chain across multiple sectors).
    const sym2 = ole.readStream('Symbol 2');
    expect(sym2.length).toBe(5017);
    // Body is filled with 0x42 ('B') after its class declaration.
    expect(sym2[sym2.length - 1]).toBe(0x42);
  });

  it('throws a specific error for a missing stream (no silent failure)', async () => {
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);
    expect(() => ole.readStream('Symbol 99')).toThrow(/stream not found/);
  });

  it('throws when given non-OLE2 bytes', () => {
    expect(() => new OLE2File(new Uint8Array([0x50, 0x4b, 0x03, 0x04]))).toThrow(
      /Not an OLE2 compound file/
    );
  });
});

describe('extractBinaryFLAInfo', () => {
  it('extracts document properties and the symbol library', async () => {
    const bytes = await loadFixtureBytes();
    const info = extractBinaryFLAInfo(bytes);

    expect(info.width).toBe(640);
    expect(info.height).toBe(480);
    expect(info.dimensionsFromPublishSettings).toBe(true);
    expect(info.frameRate).toBe(30);
    expect(info.backgroundColor).toBe('#112233');

    expect(info.streams.sort()).toEqual(['Contents', 'Symbol 1', 'Symbol 2']);

    expect(info.library).toEqual([
      { symbolNumber: 1, name: 'My Graphic', symbolType: 'graphic' },
      { symbolNumber: 2, name: 'My Clip', symbolType: 'movieclip' },
      { symbolNumber: 3, name: 'My Button', symbolType: 'button' },
    ]);
  });
});

describe('parseBinaryFLA → FLADocument', () => {
  it('produces a renderable FLADocument with mapped library symbols', async () => {
    const bytes = await loadFixtureBytes();
    const doc = parseBinaryFLA(bytes);

    expect(doc.width).toBe(640);
    expect(doc.height).toBe(480);
    expect(doc.frameRate).toBe(30);
    expect(doc.backgroundColor).toBe('#112233');

    // A single (empty) main timeline so the viewer can open the document.
    expect(doc.timelines).toHaveLength(1);
    expect(doc.timelines[0].name).toBe('Scene 1');

    // Library symbols are registered by name with correct types.
    expect(doc.symbols.size).toBe(3);
    expect(doc.symbols.get('My Graphic')?.symbolType).toBe('graphic');
    expect(doc.symbols.get('My Clip')?.symbolType).toBe('movieclip');
    expect(doc.symbols.get('My Button')?.symbolType).toBe('button');
    expect(doc.symbols.get('My Clip')?.itemID).toBe('Symbol 2');

    // No bitmaps/sounds/videos are decoded from the binary format yet.
    expect(doc.bitmaps.size).toBe(0);
    expect(doc.sounds.size).toBe(0);
    expect(doc.videos.size).toBe(0);
  });
});

describe('FLAParser.parse routing for binary FLAs', () => {
  it('detects an OLE2 binary FLA and parses it via the binary path', async () => {
    const buffer = await loadFixtureBuffer();
    const file = new File([buffer], 'binary-mx2004.fla', {
      type: 'application/octet-stream',
    });
    const parser = new FLAParser();
    const doc = await parser.parse(file);

    expect(doc.width).toBe(640);
    expect(doc.height).toBe(480);
    expect(doc.frameRate).toBe(30);
    expect(doc.symbols.size).toBe(3);
  });

  it('surfaces a clear, specific error for a binary FLA with no Contents stream', async () => {
    // Build a valid OLE2 file whose single stream is NOT "Contents", so the
    // binary parser must fail loudly rather than with the ZIP-path's generic
    // "DOMDocument.xml not found".
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);
    // Sanity: the fixture does have Contents; corrupt the name in a copy.
    const corrupted = bytes.slice();
    // Find the UTF-16LE "Contents" name inside the directory and clobber the
    // leading 'C' (0x43) so the stream is renamed and no longer matched.
    for (let i = 0; i < corrupted.length - 1; i++) {
      if (
        corrupted[i] === 0x43 && // 'C'
        corrupted[i + 1] === 0x00 &&
        corrupted[i + 2] === 0x6f && // 'o'
        corrupted[i + 4] === 0x6e // 'n'
      ) {
        corrupted[i] = 0x58; // 'X'
        break;
      }
    }
    expect(ole.hasStream('Contents')).toBe(true);
    const file = new File([corrupted.buffer], 'broken.fla', {
      type: 'application/octet-stream',
    });
    const parser = new FLAParser();
    await expect(parser.parse(file)).rejects.toThrow(/missing its "Contents" stream/);
  });
});
