import { describe, it, expect } from 'vitest';
import {
  attributeToFrames,
  decodeStreamTimeline,
  type DecodedKeyframe,
} from '../binary-timeline-decoder';
// A committed, byte-valid OLE2 binary FLA whose `Page 1` scene has ONE layer
// with three keyframes (spans 1, 3, 1 → indices 0, 1, 4), each placing a green
// square at a different x. Generated by scripts/make-timeline-fixture.mjs; it
// exercises the FULL parser → attribution pipeline (see the end-to-end test).
import timelineFlaUrl from './fixtures/binary-timeline.fla?url';
import { parseBinaryFLA } from '../binary-fla-parser';

async function loadTimelineFla(): Promise<Uint8Array> {
  const res = await fetch(timelineFlaUrl);
  return new Uint8Array(await res.arrayBuffer());
}

// ── little-endian byte builders ─────────────────────────────────────────────
function u8(...v: number[]): number[] {
  return v.map((n) => n & 0xff);
}
function u16(v: number): number[] {
  return [v & 0xff, (v >> 8) & 0xff];
}
function s16(v: number): number[] {
  return u16(v < 0 ? v + 0x10000 : v);
}
function u32(v: number): number[] {
  return [v & 0xff, (v >> 8) & 0xff, (v >> 16) & 0xff, (v >>> 24) & 0xff];
}
function s32(v: number): number[] {
  return u32(v < 0 ? v + 0x100000000 : v);
}

const NEWCLASS = [0xff, 0xff];
const NULL_TAG = [0x00, 0x00];
const INT_MIN = s32(-0x80000000);
// The CPicObj NULL-child + 2×INT_MIN point sentinel that begins every
// CPicShape / CPicFrame body and terminates the outermost page.
const SENTINEL = [...NULL_TAG, ...INT_MIN, ...INT_MIN];

function classDecl(name: string, schema = 1): number[] {
  return [...NEWCLASS, ...u16(schema), ...u16(name.length), ...name.split('').map((c) => c.charCodeAt(0))];
}
/** A back-ref tag for an already-declared class at 1-based combined index. */
function backref(idx: number): number[] {
  return u16(0x8000 | idx);
}
/** Flash CString FF FE FF <u8 charLen> <UTF-16LE>. */
function flashStr(s: string): number[] {
  const out = [0xff, 0xfe, 0xff, s.length];
  for (const ch of s) out.push(ch.charCodeAt(0) & 0xff, (ch.charCodeAt(0) >> 8) & 0xff);
  return out;
}

/**
 * A minimal empty CPicShape geometry block (shape_data): shape_data_schema,
 * edge_hint(u32), fill_count(u16)=0, line_count(u16)=0, edge terminator(u8)=0.
 * When `schema > 4` it ALSO emits the cubic32 post-stream (`s32 count=0`) that
 * Flash 8 shapes carry — the structural walk must consume it to stay aligned
 * (real `Symbol 24` frames are schema 5; without this the walk desyncs).
 */
function shapeData(schema = 3): number[] {
  const out = [...u8(schema), ...u32(0), ...u16(0), ...u16(0), ...u8(0)];
  if (schema > 4) out.push(...s32(0)); // cubic edge count = 0
  return out;
}

/** A CPicShape body: CPicObj base (schema 2: NULL child + point) + shape tail. */
function shapeBody(): number[] {
  return [
    ...u8(2, 0), // CPicObj schema=2, flags=0
    ...NULL_TAG, // empty children
    ...INT_MIN,
    ...INT_MIN, // point
    ...u8(2), // shape_schema (<=2 → capsFlag false)
    ...u32(0x10000),
    ...u32(0),
    ...u32(0),
    ...u32(0x10000),
    ...u32(0),
    ...u32(0), // identity matrix
    ...shapeData(),
  ];
}

/**
 * A CPicFrame body with frame_schema 19 (the minimal "modern" schema the walk
 * supports), a given `span` (field_18c), and an optional CPicShape child placed
 * in the frame's children list. The child's class tag is supplied by the caller
 * (NEWCLASS for the first, back-ref afterwards), since the archive registers
 * CPicShape on first use.
 */
function frameBody(span: number, childTag: number[]): number[] {
  const out: number[] = [];
  // CPicObj base: schema 2, flags 0, children list (one CPicShape) then NULL.
  out.push(...u8(2, 0));
  out.push(...childTag, ...shapeBody());
  out.push(...NULL_TAG); // end children
  out.push(...INT_MIN, ...INT_MIN); // point
  // CPicShape tail (the frame's own drawable canvas — empty, schema-5 so it
  // carries the cubic32 post-stream the walk must consume; matches real files).
  out.push(...u8(2)); // shape_schema
  out.push(...u32(0x10000), ...u32(0), ...u32(0), ...u32(0x10000), ...u32(0), ...u32(0));
  out.push(...shapeData(5));
  // CPicFrame tail, frame_schema 19.
  const fs = 19;
  out.push(...u8(fs));
  out.push(...u16(span)); // field_18c = SPAN
  out.push(...u16(0)); // field_188 (fs>2)
  out.push(...s16(0)); // field_190 (fs>1)
  out.push(...u16(0)); // sound (fs>4)
  out.push(...u16(0)); // entry count = 0 (fs>5)
  out.push(...u16(0), ...u8(0), ...u32(0), ...s32(0)); // fs>6 block
  out.push(...u16(0)); // field_248 (fs>7)
  // fs>=19 timeline sub-object FUN_8facd0: type_id=0, format_type=2 (no extra).
  out.push(...u32(0), ...u32(2));
  // fs>10 post-timeline fields.
  out.push(...u32(0), ...u32(0)); // f258, f25c
  out.push(...u32(0)); // f254 (fs>11)
  out.push(...u16(0)); // morph ReadObject null (fs>12)
  out.push(...u32(0)); // f1e4 (fs>13)
  out.push(...u16(0)); // oblist ReadObject null (fs>14)
  // fs>15 cstring only when fs>=23 (skipped); fs>19/20/22/24 skipped for fs=19.
  return out;
}

/**
 * A complete stream: 0x01 root header, CPicPage NEWCLASS + base, then one
 * CPicLayer (schema 11) whose children are the given keyframe spans. The
 * combined class table fills as: CPicPage→idx1/2, CPicLayer→3/4,
 * CPicFrame→5/6 (declared by the first frame), CPicShape→7/8 (declared by the
 * first frame's child). So later frames back-ref CPicFrame at idx 5 and later
 * shape children back-ref CPicShape at idx 7.
 */
function streamBytes(layerName: string, spans: number[]): Uint8Array {
  const out: number[] = [];
  out.push(0x01); // root header
  out.push(...classDecl('CPicPage', 1)); // combined idx 1/2
  out.push(...u8(2, 0)); // CPicPage CPicObj base: schema 2, flags 0
  out.push(...classDecl('CPicLayer', 1)); // idx 3/4 — first page child
  out.push(...u8(2, 0)); // CPicLayer CPicObj base
  spans.forEach((span, i) => {
    // CPicFrame: NEWCLASS (idx 5/6) for the first frame, back-ref for the rest.
    out.push(...(i === 0 ? classDecl('CPicFrame', 1) : backref(5)));
    // CPicShape child: NEWCLASS (idx 7/8) for the first, back-ref afterwards.
    const childTag = i === 0 ? classDecl('CPicShape', 1) : backref(7);
    out.push(...frameBody(span, childTag));
  });
  out.push(...NULL_TAG); // end layer children
  out.push(...INT_MIN, ...INT_MIN); // layer point
  // Layer tail, schema 11.
  out.push(...u8(11)); // layer_schema
  out.push(...flashStr(layerName));
  out.push(...u8(0), ...u8(0), ...u8(1)); // type=normal, locked=0, visible=1
  out.push(...u32(0xffffffff)); // color (schema>=5)
  out.push(...u32(0), ...u32(0)); // field_8c/90 (schema>=6)
  out.push(...u32(0)); // field_98 (schema>=8)
  out.push(...u8(0)); // layer_mode
  out.push(...NULL_TAG); // parent ReadObject (null)
  out.push(...u8(0)); // schema>=9 byte
  out.push(...u8(0)); // schema>=10 byte
  // Page-terminating sentinel: the layer's end-marker scan lands here so the
  // page's children loop reads its NULL tag and stops.
  out.push(...SENTINEL);
  out.push(...u8(2)); // a schema byte the end-marker validation accepts
  out.push(...NULL_TAG); // page children NULL terminator
  return Uint8Array.from(out);
}

describe('binary-timeline-decoder: decodeStreamTimeline', () => {
  it('decodes a single layer with multiple keyframes (index + duration)', () => {
    // Three keyframes spanning 1, 5, 2 frames → indices 0, 1, 6; total 8.
    const data = streamBytes('Layer 1', [1, 5, 2]);
    const tl = decodeStreamTimeline(data);
    expect(tl).not.toBeNull();
    expect(tl!.layers).toHaveLength(1);
    const layer = tl!.layers[0];
    expect(layer.name).toBe('Layer 1');
    expect(layer.schema).toBe(11);
    expect(layer.visible).toBe(true);
    expect(layer.locked).toBe(false);
    expect(layer.keyframes.map((k) => k.startIndex)).toEqual([0, 1, 6]);
    expect(layer.keyframes.map((k) => k.duration)).toEqual([1, 5, 2]);
    expect(tl!.totalFrames).toBe(8); // 6 + 2
  });

  it('records each keyframe byte range in ascending, non-overlapping order', () => {
    const data = streamBytes('Layer 1', [1, 1, 1]);
    const tl = decodeStreamTimeline(data)!;
    const kfs = tl.layers[0].keyframes;
    expect(kfs).toHaveLength(3);
    for (let i = 0; i < kfs.length; i++) {
      expect(kfs[i].bodyEnd).toBeGreaterThan(kfs[i].bodyStart);
      if (i > 0) {
        expect(kfs[i].bodyStart).toBeGreaterThanOrEqual(kfs[i - 1].bodyEnd);
      }
    }
  });

  it('returns null for a single-keyframe layer (no attribution needed)', () => {
    // A lone keyframe is handled by the existing single-frame path; the
    // confidence gate requires animation (>1 keyframe) before taking over.
    const data = streamBytes('Layer 1', [1]);
    expect(decodeStreamTimeline(data)).toBeNull();
  });

  it('returns null when the root is not a CPicPage', () => {
    const notPage = Uint8Array.from([0x01, ...classDecl('CPicSprite', 1), 0, 0]);
    expect(decodeStreamTimeline(notPage)).toBeNull();
  });

  it('returns null on a truncated / garbage stream (never throws)', () => {
    expect(decodeStreamTimeline(new Uint8Array([0x01, 0xff, 0xff]))).toBeNull();
    expect(decodeStreamTimeline(new Uint8Array(0))).toBeNull();
    // Random bytes must not throw out of the confidence gate.
    const rnd = new Uint8Array(200);
    for (let i = 0; i < rnd.length; i++) rnd[i] = (i * 37 + 11) & 0xff;
    expect(() => decodeStreamTimeline(rnd)).not.toThrow();
  });
});

describe('binary-timeline-decoder: attributeToFrames', () => {
  const kfs: DecodedKeyframe[] = [
    { startIndex: 0, duration: 1, bodyStart: 100, bodyEnd: 200 },
    { startIndex: 1, duration: 5, bodyStart: 200, bodyEnd: 350 },
    { startIndex: 6, duration: 2, bodyStart: 350, bodyEnd: 500 },
  ];

  it('places each item in the keyframe whose byte range contains it', () => {
    const items = [
      { bodyStart: 150, id: 'a' }, // → kf0
      { bodyStart: 250, id: 'b' }, // → kf1
      { bodyStart: 349, id: 'c' }, // → kf1 (just inside)
      { bodyStart: 400, id: 'd' }, // → kf2
    ];
    const { perKeyframe, unattributed } = attributeToFrames(kfs, items);
    expect(perKeyframe[0].map((i) => i.id)).toEqual(['a']);
    expect(perKeyframe[1].map((i) => i.id)).toEqual(['b', 'c']);
    expect(perKeyframe[2].map((i) => i.id)).toEqual(['d']);
    expect(unattributed).toEqual([]);
  });

  it('returns items outside every range as unattributed (never dropped)', () => {
    const items = [
      { bodyStart: 50, id: 'before' },
      { bodyStart: 600, id: 'after' },
      { bodyStart: 200, id: 'in' },
    ];
    const { perKeyframe, unattributed } = attributeToFrames(kfs, items);
    expect(perKeyframe[1].map((i) => i.id)).toEqual(['in']);
    expect(unattributed.map((i) => i.id)).toEqual(['before', 'after']);
  });
});

// End-to-end: the full parser must attribute the fixture's recovered shapes to
// the right layer + keyframe so a scrubbed frame shows ONE shape (not all three
// overlaid as the pre-issue-8 single-frame path did).
describe('parseBinaryFLA: per-frame attribution (issue #8)', () => {
  it('splits a 3-keyframe scene into distinct frames, one shape each', async () => {
    const doc = parseBinaryFLA(await loadTimelineFla());
    expect(doc.timelines).toHaveLength(1);
    const scene = doc.timelines[0];
    // Three keyframes spanning 1, 3, 1 → indices 0, 1, 4; total 5 frames.
    expect(scene.totalFrames).toBe(5);
    expect(scene.layers).toHaveLength(1);
    const layer = scene.layers[0];
    expect(layer.name).toBe('Layer 1');
    expect(layer.frames.map((f) => [f.index, f.duration])).toEqual([
      [0, 1],
      [1, 3],
      [4, 1],
    ]);
    // Each keyframe carries exactly one shape (not all three composited at once).
    for (const f of layer.frames) {
      expect(f.elements).toHaveLength(1);
      expect(f.elements[0].type).toBe('shape');
    }
    // The shapes sit at DIFFERENT x positions (the animation): 40, 240, 440 px.
    const txs = layer.frames.map((f) => {
      const el = f.elements[0];
      return el.type === 'shape' ? el.matrix.tx : NaN;
    });
    expect(txs).toEqual([40, 240, 440]);
  });
});
