import { describe, it, expect } from 'vitest';
// The committed fixture is a *synthetic* but byte-valid OLE2/CFB compound file
// in the pre-CS5 binary FLA layout (issue #8). It contains no Adobe content —
// it was generated by a minimal CFB writer and verified to round-trip through
// the `olefile` reference reader. It exercises BOTH stream paths: a small
// `Contents`/`Symbol 1` (mini-FAT) and a >4096-byte `Symbol 2` (regular FAT).
import binaryFlaUrl from './fixtures/binary-mx2004.fla?url';
// A *synthetic*, byte-valid CFB **version 4** (4096-byte sector) fixture,
// generated by scripts/gen-binary-fla-v4.mjs. v4 is the only sector size that
// distinguishes the correct `(n + 1) * sectorSize` offset from the old
// `512 + n * sectorSize` coincidence (which matches only for 512-byte v3
// sectors). Its `Contents` stream deliberately spans multiple 4096-byte
// sectors so the FAT chain + sectorOffset are genuinely exercised.
import binaryV4Url from './fixtures/binary-v4.fla?url';
// A *synthetic*, byte-valid CFB **version 3** fixture whose FAT spans 110
// sectors — one MORE than the 109 pointers that fit in the header's DIFAT
// array — so reading its `Contents` stream back REQUIRES the DIFAT-sector
// chaining loop in `parseHeader`. The uncompressed file is ~6.8 MB (the cost
// of forcing > 109 FAT sectors at 512-byte sectors), so it is committed gzipped
// (~75 KB) and inflated here via the browser's DecompressionStream. Regenerate
// with scripts/gen-binary-fla-difat.mjs; verified against Python `olefile`.
import binaryDifatUrl from './fixtures/binary-difat.fla.gz?url';
// A *synthetic*, byte-valid CFB v3 fixture whose `Page 1` and `Symbol 1`
// streams carry real CPicLayer records (the wire layout validated against 5
// real Flash MX 2004 FLAs). Generated by scripts/gen-binary-fla-layers.mjs and
// verified to round-trip through Python `olefile`. Exercises the end-to-end
// timeline/layer-structure extraction added for the issue #8 follow-up.
import binaryLayersUrl from './fixtures/binary-layers.fla?url';
import { isOLE2, OLE2File, OLE2_MAGIC } from '../ole2-reader';
import {
  extractBinaryFLAInfo,
  parseBinaryFLA,
} from '../binary-fla-parser';
import { FLAParser } from '../fla-parser';

async function loadFixtureBuffer(): Promise<ArrayBuffer> {
  const res = await fetch(binaryFlaUrl);
  return res.arrayBuffer();
}

async function loadFixtureBytes(): Promise<Uint8Array> {
  return new Uint8Array(await loadFixtureBuffer());
}

describe('isOLE2 magic detection', () => {
  it('detects the OLE2 compound-file signature', () => {
    expect(isOLE2(OLE2_MAGIC)).toBe(true);
    expect(isOLE2(new Uint8Array([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1, 0x00]))).toBe(true);
  });

  it('rejects a ZIP/XFL header ("PK") used by CS5+ FLAs', () => {
    // "PK\x03\x04" — the ZIP local-file-header signature.
    expect(isOLE2(new Uint8Array([0x50, 0x4b, 0x03, 0x04, 0x0a, 0x00]))).toBe(false);
  });

  it('rejects too-short input without throwing', () => {
    expect(isOLE2(new Uint8Array([0xd0, 0xcf]))).toBe(false);
    expect(isOLE2(new Uint8Array(0))).toBe(false);
  });
});

describe('OLE2File directory + stream reading', () => {
  it('lists the expected streams from a real-layout binary FLA', async () => {
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);
    const names = ole.listStreams().map((s) => s.name).sort();
    expect(names).toEqual(['Contents', 'Symbol 1', 'Symbol 2']);
    expect(ole.hasStream('Contents')).toBe(true);
    expect(ole.hasStream('DoesNotExist')).toBe(false);
  });

  it('reads a small (mini-FAT) stream and a large (FAT) stream correctly', async () => {
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);

    // Symbol 1 is below the 4096-byte mini-stream cutoff (mini-FAT path).
    const sym1 = ole.readStream('Symbol 1');
    expect(sym1.length).toBe(80);
    // MFC root header byte (0x01) followed by the FFFF new-class tag.
    expect(sym1[0]).toBe(0x01);
    expect(sym1[1]).toBe(0xff);
    expect(sym1[2]).toBe(0xff);

    // Symbol 2 is >4096 bytes (regular FAT chain across multiple sectors).
    const sym2 = ole.readStream('Symbol 2');
    expect(sym2.length).toBe(5017);
    // Body is filled with 0x42 ('B') after its class declaration.
    expect(sym2[sym2.length - 1]).toBe(0x42);
  });

  it('throws a specific error for a missing stream (no silent failure)', async () => {
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);
    expect(() => ole.readStream('Symbol 99')).toThrow(/stream not found/);
  });

  it('throws when given non-OLE2 bytes', () => {
    expect(() => new OLE2File(new Uint8Array([0x50, 0x4b, 0x03, 0x04]))).toThrow(
      /Not an OLE2 compound file/
    );
  });
});

describe('OLE2File CFB v4 (4096-byte sectors)', () => {
  // Keep this byte pattern IN SYNC with scripts/gen-binary-fla-v4.mjs.
  // It is a stable function of the byte index, so we can assert the entire
  // decoded stream without committing a large literal.
  const CONTENTS_SIZE = 4096 * 3 + 1234; // 13522 — spans 4 sectors of 4096
  const expectedByte = (i: number): number =>
    (i * 31 + (i >> 8) * 7 + 0x11) & 0xff;

  async function loadV4Bytes(): Promise<Uint8Array> {
    const res = await fetch(binaryV4Url);
    return new Uint8Array(await res.arrayBuffer());
  }

  it('reads a multi-sector stream from a 4096-byte-sector compound file', async () => {
    const bytes = await loadV4Bytes();
    const ole = new OLE2File(bytes);

    // The v4 fixture holds exactly one stream: a large "Contents".
    expect(ole.listStreams().map((s) => s.name)).toEqual(['Contents']);
    expect(ole.hasStream('Contents')).toBe(true);

    const contents = ole.readStream('Contents');
    expect(contents.length).toBe(CONTENTS_SIZE);

    // Spot-check sector boundaries first (cheap, pinpoints which sector is
    // misaligned if it ever regresses): start of sectors 0..3 and the tail.
    expect(contents[0]).toBe(expectedByte(0));
    expect(contents[4096]).toBe(expectedByte(4096));
    expect(contents[8192]).toBe(expectedByte(8192));
    expect(contents[12288]).toBe(expectedByte(12288));
    expect(contents[CONTENTS_SIZE - 1]).toBe(expectedByte(CONTENTS_SIZE - 1));

    // Full byte-for-byte verification across the whole multi-sector chain.
    let mismatch = -1;
    for (let i = 0; i < CONTENTS_SIZE; i++) {
      if (contents[i] !== expectedByte(i)) {
        mismatch = i;
        break;
      }
    }
    expect(mismatch).toBe(-1);
  });
});

describe('OLE2File DIFAT-sector chaining (FAT > 109 sectors)', () => {
  // Keep in sync with scripts/gen-binary-fla-difat.mjs.
  const CONTENTS_SIZE = 7102327;
  const expectedByte = (i: number): number =>
    (i * 37 + Math.floor(i / 512) * 11 + 0x29) & 0xff;

  async function loadDifatBytes(): Promise<Uint8Array> {
    const res = await fetch(binaryDifatUrl);
    const raw = new Uint8Array(await res.arrayBuffer());
    // The fixture is committed gzipped. Some servers (the vite dev server used
    // here) send `Content-Encoding: gzip` and the browser inflates it
    // transparently, so the bytes may already be the raw CFB. Detect that by
    // the OLE2 magic and only inflate when the bytes are still gzip-wrapped
    // (gzip magic 0x1f 0x8b). This keeps the loader correct regardless of
    // whether transport-level decompression happened.
    if (raw[0] === 0xd0 && raw[1] === 0xcf) {
      return raw; // already a CFB (transparently decompressed in transit)
    }
    if (raw[0] === 0x1f && raw[1] === 0x8b) {
      const stream = new Response(raw).body!.pipeThrough(
        new DecompressionStream('gzip')
      );
      return new Uint8Array(await new Response(stream).arrayBuffer());
    }
    throw new Error(
      `Unexpected DIFAT fixture bytes: leading 0x${raw[0]?.toString(16)} 0x${raw[1]?.toString(16)}`
    );
  }

  it('reads a stream whose FAT needs a chained DIFAT sector to describe', async () => {
    const bytes = await loadDifatBytes();
    // Sanity: the inflated fixture is the full ~6.8 MB CFB.
    expect(bytes.length).toBe(7160320);

    const ole = new OLE2File(bytes);
    expect(ole.listStreams().map((s) => s.name)).toEqual(['Contents']);

    const contents = ole.readStream('Contents');
    // The FULL length proves the FAT chain was followed past the 109th FAT
    // sector — without DIFAT chaining the reader sees only the first
    // 109 × 128 = 13 952 sectors and the tail is lost.
    expect(contents.length).toBe(CONTENTS_SIZE);

    // Spot-check the tail (which lives in sectors only reachable via the FAT
    // sectors listed in the DIFAT sector) and the very last byte.
    expect(contents[CONTENTS_SIZE - 1]).toBe(expectedByte(CONTENTS_SIZE - 1));
    expect(contents[7_000_000]).toBe(expectedByte(7_000_000));

    // Full byte-for-byte verification across the whole multi-sector chain.
    let mismatch = -1;
    for (let i = 0; i < CONTENTS_SIZE; i++) {
      if (contents[i] !== expectedByte(i)) {
        mismatch = i;
        break;
      }
    }
    expect(mismatch).toBe(-1);
  });
});

describe('extractBinaryFLAInfo', () => {
  it('extracts document properties and the symbol library', async () => {
    const bytes = await loadFixtureBytes();
    const info = extractBinaryFLAInfo(bytes);

    expect(info.width).toBe(640);
    expect(info.height).toBe(480);
    expect(info.dimensionsFromPublishSettings).toBe(true);
    expect(info.frameRate).toBe(30);
    expect(info.backgroundColor).toBe('#112233');

    expect(info.streams.sort()).toEqual(['Contents', 'Symbol 1', 'Symbol 2']);

    expect(info.library).toEqual([
      { symbolNumber: 1, name: 'My Graphic', symbolType: 'graphic' },
      { symbolNumber: 2, name: 'My Clip', symbolType: 'movieclip' },
      { symbolNumber: 3, name: 'My Button', symbolType: 'button' },
    ]);
  });
});

describe('parseBinaryFLA → FLADocument', () => {
  it('produces a renderable FLADocument with mapped library symbols', async () => {
    const bytes = await loadFixtureBytes();
    const doc = parseBinaryFLA(bytes);

    expect(doc.width).toBe(640);
    expect(doc.height).toBe(480);
    expect(doc.frameRate).toBe(30);
    expect(doc.backgroundColor).toBe('#112233');

    // A single (empty) main timeline so the viewer can open the document.
    expect(doc.timelines).toHaveLength(1);
    expect(doc.timelines[0].name).toBe('Scene 1');

    // Library symbols are registered by name with correct types.
    expect(doc.symbols.size).toBe(3);
    expect(doc.symbols.get('My Graphic')?.symbolType).toBe('graphic');
    expect(doc.symbols.get('My Clip')?.symbolType).toBe('movieclip');
    expect(doc.symbols.get('My Button')?.symbolType).toBe('button');
    expect(doc.symbols.get('My Clip')?.itemID).toBe('Symbol 2');

    // No bitmaps/sounds/videos are decoded from the binary format yet.
    expect(doc.bitmaps.size).toBe(0);
    expect(doc.sounds.size).toBe(0);
    expect(doc.videos.size).toBe(0);
  });
});

describe('FLAParser.parse routing for binary FLAs', () => {
  it('detects an OLE2 binary FLA and parses it via the binary path', async () => {
    const buffer = await loadFixtureBuffer();
    const file = new File([buffer], 'binary-mx2004.fla', {
      type: 'application/octet-stream',
    });
    const parser = new FLAParser();
    const doc = await parser.parse(file);

    expect(doc.width).toBe(640);
    expect(doc.height).toBe(480);
    expect(doc.frameRate).toBe(30);
    expect(doc.symbols.size).toBe(3);
  });

  it('surfaces a clear, specific error for a binary FLA with no Contents stream', async () => {
    // Build a valid OLE2 file whose single stream is NOT "Contents", so the
    // binary parser must fail loudly rather than with the ZIP-path's generic
    // "DOMDocument.xml not found".
    const bytes = await loadFixtureBytes();
    const ole = new OLE2File(bytes);
    // Sanity: the fixture does have Contents; corrupt the name in a copy.
    const corrupted = bytes.slice();
    // Find the UTF-16LE "Contents" name inside the directory and clobber the
    // leading 'C' (0x43) so the stream is renamed and no longer matched.
    for (let i = 0; i < corrupted.length - 1; i++) {
      if (
        corrupted[i] === 0x43 && // 'C'
        corrupted[i + 1] === 0x00 &&
        corrupted[i + 2] === 0x6f && // 'o'
        corrupted[i + 4] === 0x6e // 'n'
      ) {
        corrupted[i] = 0x58; // 'X'
        break;
      }
    }
    expect(ole.hasStream('Contents')).toBe(true);
    const file = new File([corrupted.buffer], 'broken.fla', {
      type: 'application/octet-stream',
    });
    const parser = new FLAParser();
    await expect(parser.parse(file)).rejects.toThrow(/missing its "Contents" stream/);
  });
});

describe('binary FLA timeline / layer-structure extraction (issue #8)', () => {
  async function loadLayersBytes(): Promise<Uint8Array> {
    const res = await fetch(binaryLayersUrl);
    return new Uint8Array(await res.arrayBuffer());
  }

  it('decodes per-scene and per-symbol layer lists from the OLE2 streams', async () => {
    const bytes = await loadLayersBytes();
    const info = extractBinaryFLAInfo(bytes);

    // Document props + library (regression: still work alongside the new data).
    expect(info.width).toBe(320);
    expect(info.height).toBe(240);
    expect(info.frameRate).toBe(30);
    expect(info.backgroundColor).toBe('#336699');
    expect(info.library).toEqual([
      { symbolNumber: 1, name: 'Box', symbolType: 'graphic' },
    ]);

    // Scene (Page 1) layers: name + type + locked + visible, in stream order.
    expect(info.scenes).toEqual([
      {
        scene: 1,
        layers: [
          { name: 'Background', schema: 11, layerType: 'normal', locked: false, visible: true },
          { name: 'Guide: helper', schema: 11, layerType: 'guide', locked: false, visible: true },
          { name: 'Actions', schema: 11, layerType: 'normal', locked: true, visible: true },
        ],
      },
    ]);

    // Symbol 1's own timeline layers.
    expect(info.symbolLayers.get(1)).toEqual([
      { name: 'Layer 1', schema: 11, layerType: 'normal', locked: false, visible: true },
      { name: 'Layer 2', schema: 11, layerType: 'normal', locked: true, visible: false },
    ]);
  });

  it('maps the decoded layers into the FLADocument the viewer renders', async () => {
    const bytes = await loadLayersBytes();
    const doc = parseBinaryFLA(bytes);

    // One timeline per scene, named "Scene N", carrying the real layer stack.
    expect(doc.timelines).toHaveLength(1);
    const scene = doc.timelines[0];
    expect(scene.name).toBe('Scene 1');
    expect(scene.layers.map((l) => l.name)).toEqual([
      'Background',
      'Guide: helper',
      'Actions',
    ]);
    // The guide layer is flagged so the viewer does not try to render it.
    expect(scene.layers[1].layerType).toBe('guide');
    expect([...scene.referenceLayers]).toEqual([1]);
    // Locked/visible flags are carried through.
    expect(scene.layers[2].name).toBe('Actions');
    expect(scene.layers[2].locked).toBe(true);
    // We do NOT fabricate frame content: each layer has exactly one empty frame.
    expect(scene.layers[0].frames).toHaveLength(1);
    expect(scene.layers[0].frames[0].elements).toEqual([]);

    // The symbol's timeline carries its own layers.
    const box = doc.symbols.get('Box');
    expect(box?.symbolType).toBe('graphic');
    expect(box?.timeline.layers.map((l) => l.name)).toEqual([
      'Layer 1',
      'Layer 2',
    ]);
    expect(box?.timeline.layers[1].visible).toBe(false);
  });

  it('routes through FLAParser.parse and yields the layered document', async () => {
    const bytes = await loadLayersBytes();
    const file = new File([bytes.buffer as ArrayBuffer], 'binary-layers.fla', {
      type: 'application/octet-stream',
    });
    const doc = await new FLAParser().parse(file);
    expect(doc.timelines[0].layers.map((l) => l.name)).toEqual([
      'Background',
      'Guide: helper',
      'Actions',
    ]);
  });
});
