import { describe, it, expect } from 'vitest';
import flaUrl from './fixtures/easing-tokens.fla?url';
import { FLAParser } from '../fla-parser';
import { FLARenderer } from '../renderer';

// Integration test for issue #11: a tiny *synthetic* .fla (committed under
// fixtures/, generated by scripts/gen-easing-fixture.mjs) that carries every
// distinct CreateJS-style ease method token observed in the reporter's real
// file — without redistributing that third-party artwork. It exercises the
// FULL path: committed asset -> FLAParser -> Tween -> FLARenderer.
const EXPECTED_TOKENS = [
  'backInOut', 'backOut', 'circIn', 'circOut', 'cubicIn', 'cubicInOut',
  'cubicOut', 'elasticOut', 'quadIn', 'quadInOut', 'quadOut', 'quartIn',
  'quartOut', 'quintIn', 'quintOut', 'sineInOut',
].sort();

describe('issue #11 easing fixture (end-to-end token coverage)', () => {
  it('parses every real ease token from the committed .fla and renders each non-linearly', async () => {
    const res = await fetch(flaUrl);
    const file = new File([await res.arrayBuffer()], 'easing-tokens.fla', {
      type: 'application/octet-stream',
    });

    const doc = await new FLAParser().parse(file);
    const layers = doc.timelines[0].layers;

    // 1) The parser must capture all 16 distinct method tokens from the asset.
    const parsed = layers
      .map((l) => l.frames[0].tweens?.find((t) => t.target === 'all')?.method)
      .filter((m): m is string => Boolean(m));
    expect([...new Set(parsed)].sort()).toEqual(EXPECTED_TOKENS);

    // 2) The real renderer must ease each one non-linearly. Sample at t=0.3
    //    (off the 0.5 symmetry axis) so symmetric InOut curves also register.
    const canvas = document.createElement('canvas');
    canvas.width = 100;
    canvas.height = 100;
    const renderer = new FLARenderer(canvas);
    const endFrame = { index: 10, duration: 1, keyMode: 0, elements: [] } as any;

    const stillLinear: string[] = [];
    for (const layer of layers) {
      const frame = layer.frames[0];
      const method = frame.tweens?.find((t) => t.target === 'all')?.method;
      // frameIndex 3 over a 10-frame span => base progress 0.3 before easing.
      const progress = (renderer as any).calculateTweenProgress(
        3,
        frame,
        endFrame,
        frame.acceleration,
        frame.tweens
      );
      if (method && Math.abs(progress - 0.3) <= 1e-3) stillLinear.push(method);
    }
    expect(stillLinear).toEqual([]);
  });
});
